### ISSUE TITLE
Looks promising!

### ISSUE THREAD

**Issue by gingerbeardman** [bbogdan-ov/pixma#1]
This looks promising, keep it up!

I'm also coming from Piskel.

I maintain my own build: https://github.com/gingerbeardman/piskel-playdate

But I am hungry for a new and modern experience

**Comment by bbogdan-ov** [comment]
Thanks for your feedback! But i probably won't continue developing js version of pixma, because it seems to me quite slow and heavy
And also in my opinion, there are too many "web desktop apps" right now
I don't want one relatively simple app to eat a lot of ram

I want to rewrite pixma in rust someday, when i gain more experience
Im sorry if you had high hopes for this project

**Comment by gingerbeardman** [comment]
no worries at all!

the important thing is to keep making stuff, keep improving, keep on pushing :)
